### ISSUE TITLE
"strava --setup" error

### ISSUE THREAD

**Issue by hickman1970** [techman83/WebService-Strava3#23]
When I run "strava --setup" and put in my client id and client secret it crashes with the following error:

Paste enter your client_id: 
01234
Paste enter your client_secret: 
01234567890123456789
'use_test_urls' is required, cannot be missing at /usr/local/share/perl/5.22.1/WebService/Strava/Auth.pm line 66.

I'm not sure if something is missing from my Perl setup, or if this is truly an error with WebService-Strava3.  Do you have any idea what might be going wrong?

Thanks!

**Comment by techman83** [comment]
Looks like an issue in 'LWP::Authen::OAuth2', which I have done a little work with before. 

https://github.com/techman83/perl-oauth2/blob/master/lib/LWP/Authen/OAuth2/ServiceProvider.pm#L51

There is a new release of LWP::Authen::OAuth2 that contains that change. I've not had a chance to look at what it is doing and if something needs to change inside of WebService::Strava.

**Comment by techman83** [comment]
@hickman1970 You can monkey patch in the meantime, but I'll send a PR on over to LWP::Authen::OAuth2;

Changing that line to:
```
    $self->copy_option($opts, 'use_test_urls') if defined $opts->{use_test_urls};
```
Will get rid of the error. Or you can roll back to .09 of the lib.

**Comment by techman83** [comment]
I've opened a PR for @domm to review, which should sort it out. domm/perl-oauth2#5

**Comment by techman83** [comment]
@hickman1970 LWP::Authen::OAuth2 was updated and released, so this will be all good now. Update that and you should be good to go.
