### ISSUE TITLE
Strava has changed the API to use refresh tokens, so the library no longer works.

### ISSUE THREAD

**Issue by jeffrey-friedl** [techman83/WebService-Strava3#26]
The underlying OAuth2 library can handle refresh tokens, but to use it the code needs to be refactored a bit to save access tokens from time to time, it seems.

**Comment by techman83** [comment]
I don't really write a lot of Perl in my day job anymore and don't really use the Strava API as much, patches would be welcome though.

**Comment by jeffrey-friedl** [comment]
FYI, I've got it working by simply changing the scope in WebService/Strava/Auth.pm from "view_private,write" to "activity:read_all,activity:write,profile:write,profile:read_all",  and rerunning the setup.

It remains to be seen whether the token-refresh stuff will work, or a file-write hook needs to be added. I'll wait until my stuff breaks to find out :-D

**Comment by jeffrey-friedl** [comment]
Oh, just to follow up on this.... that one change was all that was required to get things working.

**Comment by techman83** [comment]
Oh Neat! Do you think you could submit a PR? Or provide a working patch? I don't do a lot with Perl these days and I've been procrastinating adding the change as a result.

**Comment by jeffrey-friedl** [comment]
I'm not familiar with github and pull requests, but the change is literally as simple as updating one string (on line 41 of Auth.pm), as described above.    Here's a patch file:

[patchfile.txt](https://github.com/techman83/WebService-Strava3/files/4906159/patchfile.txt)
